on:
  push:
    branches: master

name: TweetIt

jobs:
  tweetit:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.1'
      - name: TweetIt
        run: |
          Rscript -e 'install.packages("rtweet")' \
                  -e '-e 'if (any(grepl("-tweetit", rtweet::get_timeline("kearneymw", n = 20, token = rtweet::create_token("rstats2twitter", consumer_key = rtweet:::decript_key(), consumer_secret = rtweet:::decript_secret(), access_secret = "${{secrets.TWITTER_ACCESS_SECRET}}", access_token = "${{secrets.TWITTER_ACCESS_TOKEN}}", set_renv = FALSE))[["text"]]))) cat("ALREADY TWEETED RECENTLY") else rtweet::post_tweet("I pushed a commit to ${{github.repository}}. Check it out: https://github.com/${{github.repository}}/commits/${{github.sha}} -tweetit", token = rtweet::create_token("rstats2twitter", consumer_key = rtweet:::decript_key(), consumer_secret = rtweet:::decript_secret(), access_secret = "${{secrets.TWITTER_ACCESS_SECRET}}", access_token = "${{secrets.TWITTER_ACCESS_TOKEN}}", set_renv = FALSE))'''

