on:
  push:
    branches: master

name: TweetIt

jobs:
  tweetit:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.1'
      - name: TweetIt
        run: |
          Rscript -e 'install.packages("rtweet")' \
                  -e 'if (any(grepl("-tweetit", rtweet::get_timeline("kearneymw", n = 100, token = rtweet::create_token("rstats2twitter", consumer_key = rtweet:::decript_key(), consumer_secret = rtweet:::decript_secret(), access_secret = "${{secrets.TWITTER_ACCESS_SECRET}}", access_token = "${{secrets.TWITTER_ACCESS_TOKEN}}", set_renv = FALSE))[["text"]]))) TRUE else rtweet::post_tweet(paste0("I pushed an commit to tweetbotornot2 -m \"", system("cat .git/COMMIT_EDITMSG", intern = TRUE), ".\" Check it out: https://github.com/mkearney/tweetbotornot2 -tweetit"), token = rtweet::create_token("rstats2twitter", consumer_key = rtweet:::decript_key(), consumer_secret = rtweet:::decript_secret(), access_secret = "${{secrets.TWITTER_ACCESS_SECRET}}", access_token = "${{secrets.TWITTER_ACCESS_TOKEN}}", set_renv = FALSE))'
